/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConfigSchema {
  /**
   * Flags to pass to slang
   */
  flags?: string | null
  /**
   * Globs of what to index
   */
  indexGlobs?: string[] | null
  /**
   * Directories to exclude
   */
  excludeDirs?: string[] | null
  /**
   * Globs for build.f files
   */
  buildGlobs?: string[] | null
  /**
   * Thread count to use for indexing
   */
  indexingThreads?: number | null
  /**
   * Thread count to use for parsing
   */
  parsingThreads?: number | null
  /**
   * Build file
   */
  build?: string | null
  /**
   * Waveform to build file pattern
   */
  buildPattern?: string | null
  /**
   * Waveform viewer command ({} will be replaced with the WCP port)
   */
  wcpCommand?: string | null
  [k: string]: unknown
}
