/* tslint:disable */
/**
 * This file was automatically generated by schema-to-ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run `pnpm genconfig` to regenerate this file.
 */

export interface Config {
  /** Flags to pass to slang */
  flags?: string
  /** Globs of what to index. By default will index all sv and svh files in the workspace. */
  indexGlobs?: string[]
  /** Directories to exclude */
  excludeDirs?: string[]
  /** Thread count to use for indexing */
  indexingThreads?: number
  /** Thread count to use for parsing */
  parsingThreads?: number
  /** Build file to use */
  build?: string | null
  /** Build file glob pattern, e.g. `builds/{}.f`. Used for selecting build files. */
  buildPattern?: string | null
  /** Waveform file glob to open given a build. Name and top variables can be passed with {name}, {top}) */
  wavesPattern?: string | null
  /** Waveform viewer command ({} will be replaced with the WCP port), used for direct wcp connection with neovim and surfer. */
  wcpCommand?: string | null
  inlayHints?: Config__InlayHints
}

export interface Config__InlayHints {
  /** Hints for port types */
  portTypes?: boolean
  /** Hints for names of ordered ports and params */
  orderedInstanceNames?: boolean
  /** Hints for port names in wildcard (.*) ports */
  wildcardNames?: boolean
  /** Hints for function argument names */
  funcArgNames?: boolean
  /** Hints for macro argument names */
  macroArgNames?: boolean
}
