/* tslint:disable */
/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically @generated by scripts/genconfig.py.
 * DO NOT MODIFY IT BY HAND. Instead, modify Config.h and run scripts/genconfig.py
 */

export interface Config {
  /** Flags to pass to slang */
  flags?: string
  /** Globs of what to index. By default will index all sv and svh files in the workspace. */
  indexGlobs?: string[]
  /** Directories to exclude */
  excludeDirs?: string[]
  /** Thread count to use for indexing */
  indexingThreads?: number
  /** Thread count to use for parsing */
  parsingThreads?: number
  /** Build file to use */
  build?: string | null
  /** Build file glob pattern, e.g. `builds/{}.f`. Used for selecting build files. */
  buildPattern?: string | null
  /** Whether build files use paths relative to that file */
  buildRelativePaths?: boolean
  /** Waveform file glob to open given a build. Name and top variables can be passed with {name}, {top}) */
  wavesPattern?: string | null
  /** Waveform viewer command ({} will be replaced with the WCP port), used for direct wcp connection with neovim and surfer. */
  wcpCommand?: string | null
  /** Inline hints for things like ordered arguments, wildcard ports, and others */
  inlayHints?: Config__InlayHints
}

export interface Config__InlayHints {
  /** Hints for port types */
  portTypes?: boolean
  /** Hints for names of ordered ports and params */
  orderedInstanceNames?: boolean
  /** Hints for port names in wildcard (.*) ports */
  wildcardNames?: boolean
  /** Function argument hints: 0=off, N=only calls with >=N args */
  funcArgNames?: number
  /** Macro argument hints: 0=off, N=only calls with >=N args */
  macroArgNames?: number
}
