//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by gen_sv_snippets.py from syntax.yaml.
//     Do not edit this file directly.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "completions/CompletionContext.h"
#include <string_view>

using namespace server;

struct SVSnippet {
    std::string_view label;
    std::string_view filterText;
    std::string_view insertText;
    std::string_view documentation;
    CompletionContextMask context;
};

static constexpr SVSnippet SV_MODULE_MEMBER_SNIPPETS[] = {
    {
        .label = "logic",
        .filterText = "logic",
        .insertText = "logic",
        .documentation = "`logic`\n"
                         "\n"
                         "```systemverilog\n"
                         "logic\n"
                         "```",
        .context = toMask(CompletionContextKind::Unknown),
    },
    {
        .label = "assign",
        .filterText = "assign",
        .insertText = "assign",
        .documentation = "`assign`\n"
                         "\n"
                         "```systemverilog\n"
                         "assign\n"
                         "```",
        .context = toMask(CompletionContextKind::Unknown),
    },
    {
        .label = "wire",
        .filterText = "wire",
        .insertText = "wire",
        .documentation = "`wire`\n"
                         "\n"
                         "```systemverilog\n"
                         "wire\n"
                         "```",
        .context = toMask(CompletionContextKind::Unknown),
    },
    {
        .label = "reg",
        .filterText = "reg",
        .insertText = "reg",
        .documentation = "`reg`\n"
                         "\n"
                         "```systemverilog\n"
                         "reg\n"
                         "```",
        .context = toMask(CompletionContextKind::Unknown),
    },
    {
        .label = "bit",
        .filterText = "bit",
        .insertText = "bit ${1:bit_name} = ${2:value};",
        .documentation = "`bit`\n"
                         "\n"
                         "```systemverilog\n"
                         "bit ${1:bit_name} = ${2:value};\n"
                         "```",
        .context = toMask(CompletionContextKind::Unknown),
    },
    {
        .label = "int",
        .filterText = "int",
        .insertText = "int ${1:int_name} = ${2:value};",
        .documentation = "`int`\n"
                         "\n"
                         "```systemverilog\n"
                         "int ${1:int_name} = ${2:value};\n"
                         "```",
        .context = toMask(CompletionContextKind::Unknown),
    },
    {
        .label = "shortint",
        .filterText = "shortint",
        .insertText = "shortint ${1:name} = ${2:value};",
        .documentation = "`shortint`\n"
                         "\n"
                         "```systemverilog\n"
                         "shortint ${1:name} = ${2:value};\n"
                         "```",
        .context = toMask(CompletionContextKind::Unknown),
    },
    {
        .label = "longint",
        .filterText = "longint",
        .insertText = "longint ${1:name} = ${2:value};",
        .documentation = "`longint`\n"
                         "\n"
                         "```systemverilog\n"
                         "longint ${1:name} = ${2:value};\n"
                         "```",
        .context = toMask(CompletionContextKind::Unknown),
    },
    {
        .label = "byte",
        .filterText = "byte",
        .insertText = "byte ${1:byte_name} = ${2:value};",
        .documentation = "`byte`\n"
                         "\n"
                         "```systemverilog\n"
                         "byte ${1:byte_name} = ${2:value};\n"
                         "```",
        .context = toMask(CompletionContextKind::Unknown),
    },
    {
        .label = "struct",
        .filterText = "struct",
        .insertText = "struct {\n"
                      "\t$0\n"
                      "} ${1:struct_name};",
        .documentation = "`struct { ... } name`\n"
                         "\n"
                         "```systemverilog\n"
                         "struct {\n"
                         "\t$0\n"
                         "} ${1:struct_name};\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember),
    },
    {
        .label = "typedef struct",
        .filterText = "typedef struct",
        .insertText = "typedef struct {\n"
                      "\t$0\n"
                      "} ${1:struct_name};",
        .documentation = "`typedef struct { ... } name`\n"
                         "\n"
                         "```systemverilog\n"
                         "typedef struct {\n"
                         "\t$0\n"
                         "} ${1:struct_name};\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember) |
                   toMask(CompletionContextKind::CompilationUnit),
    },
    {
        .label = "struct packed",
        .filterText = "struct packed",
        .insertText = "struct packed {\n"
                      "\t$0\n"
                      "} ${1:struct_name};",
        .documentation = "`struct packed { ... } name`\n"
                         "\n"
                         "```systemverilog\n"
                         "struct packed {\n"
                         "\t$0\n"
                         "} ${1:struct_name};\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember),
    },
    {
        .label = "typedef struct packed",
        .filterText = "typedef struct packed",
        .insertText = "typedef struct packed {\n"
                      "\t$0\n"
                      "} ${1:struct_name};",
        .documentation = "`typedef struct packed { ... } name`\n"
                         "\n"
                         "```systemverilog\n"
                         "typedef struct packed {\n"
                         "\t$0\n"
                         "} ${1:struct_name};\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember) |
                   toMask(CompletionContextKind::CompilationUnit),
    },
    {
        .label = "enum",
        .filterText = "enum",
        .insertText = "enum {\n"
                      "\t$0\n"
                      "} ${1:struct_name};",
        .documentation = "`enum { ... } name`\n"
                         "\n"
                         "```systemverilog\n"
                         "enum {\n"
                         "\t$0\n"
                         "} ${1:struct_name};\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember),
    },
    {
        .label = "typedef enum",
        .filterText = "typedef enum",
        .insertText = "typedef enum {\n"
                      "\t$0\n"
                      "} ${1:struct_name};",
        .documentation = "`typedef enum { ... } name`\n"
                         "\n"
                         "```systemverilog\n"
                         "typedef enum {\n"
                         "\t$0\n"
                         "} ${1:struct_name};\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember) |
                   toMask(CompletionContextKind::CompilationUnit),
    },
    {
        .label = "union",
        .filterText = "union",
        .insertText = "union {\n"
                      "\t$0\n"
                      "} ${1:struct_name};",
        .documentation = "`union { ... } name`\n"
                         "\n"
                         "```systemverilog\n"
                         "union {\n"
                         "\t$0\n"
                         "} ${1:struct_name};\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember),
    },
    {
        .label = "union packed",
        .filterText = "union packed",
        .insertText = "union packed {\n"
                      "\t$0\n"
                      "} ${1:struct_name};",
        .documentation = "`union packed { ... } name`\n"
                         "\n"
                         "```systemverilog\n"
                         "union packed {\n"
                         "\t$0\n"
                         "} ${1:struct_name};\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember),
    },
    {
        .label = "typedef union",
        .filterText = "typedef union",
        .insertText = "typedef union {\n"
                      "\t$0\n"
                      "} ${1:struct_name};",
        .documentation = "`typedef union { ... } name`\n"
                         "\n"
                         "```systemverilog\n"
                         "typedef union {\n"
                         "\t$0\n"
                         "} ${1:struct_name};\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember) |
                   toMask(CompletionContextKind::CompilationUnit),
    },
    {
        .label = "typedef union packed",
        .filterText = "typedef union packed",
        .insertText = "typedef union packed {\n"
                      "\t$0\n"
                      "} ${1:struct_name};",
        .documentation = "`typedef union packed { ... } name`\n"
                         "\n"
                         "```systemverilog\n"
                         "typedef union packed {\n"
                         "\t$0\n"
                         "} ${1:struct_name};\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember) |
                   toMask(CompletionContextKind::CompilationUnit),
    },
    {
        .label = "fork join",
        .filterText = "fork join",
        .insertText = "fork\n"
                      "\t$0\n"
                      "join",
        .documentation = "`fork ... join`\n"
                         "\n"
                         "```systemverilog\n"
                         "fork\n"
                         "\t$0\n"
                         "join\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember),
    },
    {
        .label = "always_comb",
        .filterText = "always_comb",
        .insertText = "always_comb begin\n"
                      "\t$0\n"
                      "end",
        .documentation = "`always_comb begin ... end`\n"
                         "\n"
                         "```systemverilog\n"
                         "always_comb begin\n"
                         "\t$0\n"
                         "end\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember),
    },
    {
        .label = "always_latch",
        .filterText = "always_latch",
        .insertText = "always_latch begin\n"
                      "\t$0\n"
                      "end",
        .documentation = "`always_latch begin ... end`\n"
                         "\n"
                         "```systemverilog\n"
                         "always_latch begin\n"
                         "\t$0\n"
                         "end\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember),
    },
    {
        .label = "begin end",
        .filterText = "begin end",
        .insertText = "begin\n"
                      "\t$0\n"
                      "end",
        .documentation = "`begin ... end`\n"
                         "\n"
                         "```systemverilog\n"
                         "begin\n"
                         "\t$0\n"
                         "end\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember),
    },
    {
        .label = "case",
        .filterText = "case",
        .insertText = "case (${0:expression})\n"
                      "\t${1:expression_case}: ${2:statement}\n"
                      "endcase",
        .documentation = "`case ... ${endcase}`\n"
                         "\n"
                         "```systemverilog\n"
                         "case (${0:expression})\n"
                         "\t${1:expression_case}: ${2:statement}\n"
                         "endcase\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
    {
        .label = "casez",
        .filterText = "casez",
        .insertText = "casez (${0:expression})\n"
                      "\t${1:expression_case}: ${2:statement}\n"
                      "endcase",
        .documentation = "`casez ... ${endcase}`\n"
                         "\n"
                         "```systemverilog\n"
                         "casez (${0:expression})\n"
                         "\t${1:expression_case}: ${2:statement}\n"
                         "endcase\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
    {
        .label = "casex",
        .filterText = "casex",
        .insertText = "casex (${0:expression})\n"
                      "\t${1:expression_case}: ${2:statement}\n"
                      "endcase",
        .documentation = "`casex ... ${endcase}`\n"
                         "\n"
                         "```systemverilog\n"
                         "casex (${0:expression})\n"
                         "\t${1:expression_case}: ${2:statement}\n"
                         "endcase\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
    {
        .label = "unique case",
        .filterText = "unique case",
        .insertText = "unique case (${0:expression})\n"
                      "\t${1:expression_case}: ${2:statement}\n"
                      "endcase",
        .documentation = "`unique case ... ${endcase}`\n"
                         "\n"
                         "```systemverilog\n"
                         "unique case (${0:expression})\n"
                         "\t${1:expression_case}: ${2:statement}\n"
                         "endcase\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
    {
        .label = "unique casez",
        .filterText = "unique casez",
        .insertText = "unique casez (${0:expression})\n"
                      "\t${1:expression_case}: ${2:statement}\n"
                      "endcase",
        .documentation = "`unique casez ... ${endcase}`\n"
                         "\n"
                         "```systemverilog\n"
                         "unique casez (${0:expression})\n"
                         "\t${1:expression_case}: ${2:statement}\n"
                         "endcase\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
    {
        .label = "unique casex",
        .filterText = "unique casex",
        .insertText = "unique casex (${0:expression})\n"
                      "\t${1:expression_case}: ${2:statement}\n"
                      "endcase",
        .documentation = "`unique casex ... ${endcase}`\n"
                         "\n"
                         "```systemverilog\n"
                         "unique casex (${0:expression})\n"
                         "\t${1:expression_case}: ${2:statement}\n"
                         "endcase\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
    {
        .label = "unique0 case",
        .filterText = "unique0 case",
        .insertText = "unique0 case (${0:expression})\n"
                      "\t${1:expression_case}: ${2:statement}\n"
                      "endcase",
        .documentation = "`unique0 case ... ${endcase}`\n"
                         "\n"
                         "```systemverilog\n"
                         "unique0 case (${0:expression})\n"
                         "\t${1:expression_case}: ${2:statement}\n"
                         "endcase\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
    {
        .label = "unique0 casez",
        .filterText = "unique0 casez",
        .insertText = "unique0 casez (${0:expression})\n"
                      "\t${1:expression_case}: ${2:statement}\n"
                      "endcase",
        .documentation = "`unique0 casez ... ${endcase}`\n"
                         "\n"
                         "```systemverilog\n"
                         "unique0 casez (${0:expression})\n"
                         "\t${1:expression_case}: ${2:statement}\n"
                         "endcase\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
    {
        .label = "unique0 casex",
        .filterText = "unique0 casex",
        .insertText = "unique0 casex (${0:expression})\n"
                      "\t${1:expression_case}: ${2:statement}\n"
                      "endcase",
        .documentation = "`unique0 casex ... ${endcase}`\n"
                         "\n"
                         "```systemverilog\n"
                         "unique0 casex (${0:expression})\n"
                         "\t${1:expression_case}: ${2:statement}\n"
                         "endcase\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
    {
        .label = "priority case",
        .filterText = "priority case",
        .insertText = "priority case (${0:expression})\n"
                      "\t${1:expression_case}: ${2:statement}\n"
                      "endcase",
        .documentation = "`priority case ... ${endcase}`\n"
                         "\n"
                         "```systemverilog\n"
                         "priority case (${0:expression})\n"
                         "\t${1:expression_case}: ${2:statement}\n"
                         "endcase\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
    {
        .label = "priority casez",
        .filterText = "priority casez",
        .insertText = "priority casez (${0:expression})\n"
                      "\t${1:expression_case}: ${2:statement}\n"
                      "endcase",
        .documentation = "`priority casez ... ${endcase}`\n"
                         "\n"
                         "```systemverilog\n"
                         "priority casez (${0:expression})\n"
                         "\t${1:expression_case}: ${2:statement}\n"
                         "endcase\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
    {
        .label = "priority casex",
        .filterText = "priority casex",
        .insertText = "priority casex (${0:expression})\n"
                      "\t${1:expression_case}: ${2:statement}\n"
                      "endcase",
        .documentation = "`priority casex ... ${endcase}`\n"
                         "\n"
                         "```systemverilog\n"
                         "priority casex (${0:expression})\n"
                         "\t${1:expression_case}: ${2:statement}\n"
                         "endcase\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
    {
        .label = "class",
        .filterText = "class",
        .insertText = "class ${1:className};\n"
                      "\tfunction new();\n"
                      "\t\t$0\n"
                      "\tendfunction : new\n"
                      "endclass : $1",
        .documentation = "`class name; ... endclass`\n"
                         "\n"
                         "```systemverilog\n"
                         "class ${1:className};\n"
                         "\tfunction new();\n"
                         "\t\t$0\n"
                         "\tendfunction : new\n"
                         "endclass : $1\n"
                         "```",
        .context = toMask(CompletionContextKind::CompilationUnit),
    },
    {
        .label = "class extends",
        .filterText = "class extends",
        .insertText = "class ${1:className} extends ${2:superClass};\n"
                      "\tfunction new();\n"
                      "\t\t$0\n"
                      "\tendfunction : new\n"
                      "endclass : $1",
        .documentation = "`class name extends super; ... endclass`\n"
                         "\n"
                         "```systemverilog\n"
                         "class ${1:className} extends ${2:superClass};\n"
                         "\tfunction new();\n"
                         "\t\t$0\n"
                         "\tendfunction : new\n"
                         "endclass : $1\n"
                         "```",
        .context = toMask(CompletionContextKind::CompilationUnit),
    },
    {
        .label = "task",
        .filterText = "task",
        .insertText = "task ${1:automatic} ${2:taskName}(${3:arguments});\n"
                      "  $0\n"
                      "endtask : $1",
        .documentation = "`task name; ... endtask`\n"
                         "\n"
                         "```systemverilog\n"
                         "task ${1:automatic} ${2:taskName}(${3:arguments});\n"
                         "  $0\n"
                         "endtask : $1\n"
                         "```",
        .context = toMask(CompletionContextKind::CompilationUnit) |
                   toMask(CompletionContextKind::ModuleMember),
    },
    {
        .label = "package",
        .filterText = "package",
        .insertText = "package ${1:package_name}\n"
                      "\t$2\n"
                      "endpackage : $1",
        .documentation = "`package name; ... endpackage`\n"
                         "\n"
                         "```systemverilog\n"
                         "package ${1:package_name}\n"
                         "\t$2\n"
                         "endpackage : $1\n"
                         "```",
        .context = toMask(CompletionContextKind::CompilationUnit),
    },
    {
        .label = "import",
        .filterText = "import",
        .insertText = "import ${1:name}::${2:scope};",
        .documentation = "`import name::scope`\n"
                         "\n"
                         "```systemverilog\n"
                         "import ${1:name}::${2:scope};\n"
                         "```",
        .context = toMask(CompletionContextKind::CompilationUnit),
    },
    {
        .label = "interface",
        .filterText = "interface",
        .insertText = "interface ${1:interfacename};\n"
                      "\t$0\n"
                      "endinterface : $1",
        .documentation = "`interface name; ... endinterface`\n"
                         "\n"
                         "```systemverilog\n"
                         "interface ${1:interfacename};\n"
                         "\t$0\n"
                         "endinterface : $1\n"
                         "```",
        .context = toMask(CompletionContextKind::CompilationUnit),
    },
    {
        .label = "modport",
        .filterText = "modport",
        .insertText = "modport ${1:identifier} (\n"
                      "input ${2:input_ports},\n"
                      "output ${3:output_ports}\n"
                      ");",
        .documentation = "`modport name (input ports_in, output ports_out);`\n"
                         "\n"
                         "```systemverilog\n"
                         "modport ${1:identifier} (\n"
                         "input ${2:input_ports},\n"
                         "output ${3:output_ports}\n"
                         ");\n"
                         "```",
        .context = toMask(CompletionContextKind::ModuleMember),
    },
    {
        .label = "display",
        .filterText = "display",
        .insertText = "\\$display(\"$1\"$2);$0",
        .documentation = "`$display(\"...\", params...)`\n"
                         "\n"
                         "```systemverilog\n"
                         "\\$display(\"$1\"$2);$0\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
    {
        .label = "queue",
        .filterText = "queue",
        .insertText = "${1:data_type} ${2:queue_name}[\\$];",
        .documentation = "`insert queue.`\n"
                         "\n"
                         "```systemverilog\n"
                         "${1:data_type} ${2:queue_name}[\\$];\n"
                         "```",
        .context = toMask(CompletionContextKind::Unknown),
    },
    {
        .label = "mailbox",
        .filterText = "mailbox",
        .insertText = "mailbox mbx\n"
                      "${1:mbx = new();}",
        .documentation = "`insert mailbox instance`\n"
                         "\n"
                         "```systemverilog\n"
                         "mailbox mbx\n"
                         "${1:mbx = new();}\n"
                         "```",
        .context = toMask(CompletionContextKind::Unknown),
    },
    {
        .label = "assert",
        .filterText = "assert",
        .insertText = "assert (${1:condition}) $2\n"
                      "else   ${3:error_process}",
        .documentation = "`insert assert() ... else ...`\n"
                         "\n"
                         "```systemverilog\n"
                         "assert (${1:condition}) $2\n"
                         "else   ${3:error_process}\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
    {
        .label = "always_ff",
        .filterText = "always_ff",
        .insertText = "always_ff @($0) begin\n"
                      "\t$1\n"
                      "end",
        .documentation = "`always_ff @(...) ... end`\n"
                         "\n"
                         "```systemverilog\n"
                         "always_ff @($0) begin\n"
                         "\t$1\n"
                         "end\n"
                         "```",
        .context = toMask(CompletionContextKind::Procedural),
    },
};
