//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by gen_sv_snippets.py from sv_snippets.yaml.
//     Do not edit this file directly.
// </auto-generated>
//------------------------------------------------------------------------------

struct SVSnippet {
    std::string_view label;
    std::string_view filterText;
    std::string_view insertText;
    std::string_view documentation;
};

/// List of SystemVerilog keywords suitable for prepending to the LHS of an expression.
static constexpr std::string_view SV_MODULE_MEMBER_KEYWORDS[] = {
    "logic",
    "assign",
    "wire",
    "reg",
};

static constexpr SVSnippet SV_MODULE_MEMBER_SNIPPETS[] = {
    {
        .label = "bit",
        .filterText = "bit",
        .insertText = "bit ${1:bit_name} = ${2:value};",
        .documentation = "",
    },
    {
        .label = "int",
        .filterText = "int",
        .insertText = "int ${1:int_name} = ${2:value};",
        .documentation = "",
    },
    {
        .label = "shortint",
        .filterText = "shortint",
        .insertText = "shortint ${1:name} = ${2:value};",
        .documentation = "",
    },
    {
        .label = "longint",
        .filterText = "longint",
        .insertText = "longint ${1:name} = ${2:value};",
        .documentation = "",
    },
    {
        .label = "byte",
        .filterText = "byte",
        .insertText = "byte ${1:byte_name} = ${2:value};",
        .documentation = "",
    },
    {
        .label = "struct",
        .filterText = "struct",
        .insertText = "struct {\n"
                      "\t$0\n"
                      "} ${1:struct_name};",
        .documentation = "struct { ... } name",
    },
    {
        .label = "typedef struct",
        .filterText = "typedef struct",
        .insertText = "typedef struct {\n"
                      "\t$0\n"
                      "} ${1:struct_name};",
        .documentation = "typedef struct { ... } name",
    },
    {
        .label = "struct packed",
        .filterText = "struct packed",
        .insertText = "struct packed {\n"
                      "\t$0\n"
                      "} ${1:struct_name};",
        .documentation = "struct packed { ... } name",
    },
    {
        .label = "typedef struct packed",
        .filterText = "typedef struct packed",
        .insertText = "typedef struct packed {\n"
                      "\t$0\n"
                      "} ${1:struct_name};",
        .documentation = "typedef struct packed { ... } name",
    },
    {
        .label = "enum",
        .filterText = "enum",
        .insertText = "enum ${1:data_type} { $0 } ${2:name};",
        .documentation = "enum (data_type) { ... } name",
    },
    {
        .label = "typedef enum",
        .filterText = "typedef enum",
        .insertText = "typedef enum ${1:data_type} { $0 } ${2:name};",
        .documentation = "typedef enum (data_type) { ... } name",
    },
    {
        .label = "class",
        .filterText = "class",
        .insertText = "class ${1:className};\n"
                      "\tfunction new();\n"
                      "\t\t$0\n"
                      "\tendfunction : new\n"
                      "endclass : $1",
        .documentation = "class name; ... endclass",
    },
    {
        .label = "class extends",
        .filterText = "class",
        .insertText = "class ${1:className} extends ${2:superClass};\n"
                      "\tfunction new();\n"
                      "\t\t$0\n"
                      "\tendfunction : new\n"
                      "endclass : $1",
        .documentation = "class name extends super; ... endclass",
    },
    {
        .label = "task",
        .filterText = "task",
        .insertText = "task ${1:automatic} ${2:taskName}(${3:arguments});\n"
                      "  $0\n"
                      "endtask : $1",
        .documentation = "task name; ... endtask",
    },
    {
        .label = "package",
        .filterText = "package",
        .insertText = "package ${1:package_name}\n"
                      "\t$2\n"
                      "endpackage : $1",
        .documentation = "package name; ... endpackage",
    },
    {
        .label = "import",
        .filterText = "import",
        .insertText = "import ${1:name}::${2:scope};",
        .documentation = "import name::scope",
    },
    {
        .label = "interface",
        .filterText = "interface",
        .insertText = "interface ${1:interfacename};\n"
                      "\t$0\n"
                      "endinterface : $1",
        .documentation = "interface name; ... endinterface",
    },
    {
        .label = "modport",
        .filterText = "modport",
        .insertText = "modport ${1:identifier} (\n"
                      "input ${2:input_ports},\n"
                      "output ${3:output_ports}\n"
                      ");",
        .documentation = "modport name (input ports_in, output ports_out); ",
    },
    {
        .label = "display",
        .filterText = "display",
        .insertText = "\\$display(\"$1\"$2);$0",
        .documentation = "$display(\"...\", params...)",
    },
    {
        .label = "queue",
        .filterText = "queue",
        .insertText = "${1:data_type} ${2:queue_name}[\\$];",
        .documentation = "insert queue.",
    },
    {
        .label = "mailbox",
        .filterText = "mailbox",
        .insertText = "mailbox mbx\n"
                      "${1:mbx = new();}",
        .documentation = "insert mailbox instance",
    },
    {
        .label = "assert",
        .filterText = "assert",
        .insertText = "assert (${1:condition}) $2\n"
                      "else   ${3:error_process}",
        .documentation = "insert assert() ... else ...",
    },
    {
        .label = "always_ff",
        .filterText = "always_ff",
        .insertText = "always_ff @($0) begin\n"
                      "\t$1\n"
                      "end",
        .documentation = "",
    },
    {
        .label = "fork join",
        .filterText = "fork join",
        .insertText = "fork\n"
                      "\t$0\n"
                      "join",
        .documentation = "fork ... join",
    },
    {
        .label = "always_comb",
        .filterText = "always_comb",
        .insertText = "always_comb begin\n"
                      "\t$0\n"
                      "end",
        .documentation = "always_comb begin ... end",
    },
    {
        .label = "always_latch",
        .filterText = "always_latch",
        .insertText = "always_latch begin\n"
                      "\t$0\n"
                      "end",
        .documentation = "always_latch begin ... end",
    },
};
