#!/usr/bin/env node
/**
 * Simple JSON Schema to TypeScript converter
 * Handles the specific needs of our config schema
 */
const fs = require('fs')
const path = require('path')

const schemaPath = path.join(__dirname, '../resources/config.schema.json')
const outPath = path.join(__dirname, '../src/config.gen.ts')

const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'))

// Support both $defs (draft 2020-12) and definitions (draft-07)
const definitions = schema.$defs || schema.definitions || {}

function typeFromSchema(s) {
  if (s.$ref) {
    const refName = s.$ref.split('/').pop()
    return refName
  }

  if (s.type === 'string') return 'string'
  if (s.type === 'integer' || s.type === 'number') return 'number'
  if (s.type === 'boolean') return 'boolean'
  if (s.type === 'null') return 'null'

  if (s.type === 'array') {
    const items = s.items ? typeFromSchema(s.items) : 'unknown'
    return `${items}[]`
  }

  if (s.anyOf) {
    return s.anyOf.map((t) => typeFromSchema(t)).join(' | ')
  }

  if (s.type === 'object' && s.properties) {
    const props = Object.entries(s.properties)
      .map(([key, val]) => {
        const propType = typeFromSchema(val)
        const desc = val.description ? `\n  /** ${val.description} */` : ''
        return `${desc}\n  "${key}"?: ${propType};`
      })
      .join('\n')
    return `{\n${props}\n}`
  }

  return 'unknown'
}

function generateInterface(name, schemaDef) {
  const props = Object.entries(schemaDef.properties || {})
    .map(([key, val]) => {
      const propType = typeFromSchema(val)
      const desc = val.description ? `/** ${val.description} */\n  ` : ''
      return `  ${desc}${key}?: ${propType};`
    })
    .join('\n')

  return `export interface ${name} {\n${props}\n}`
}

let output = '/* tslint:disable */\n'
output += '/**\n'
output += ' * This file was automatically generated by schema-to-ts.\n'
output += ' * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,\n'
output += ' * and run `pnpm genconfig` to regenerate this file.\n'
output += ' */\n\n'

// Generate interfaces for all definitions
for (const [name, def] of Object.entries(definitions)) {
  output += generateInterface(name, def) + '\n\n'
}

fs.writeFileSync(outPath, output)
console.log(`Generated ${outPath}`)
