#!/usr/bin/env python3
"""
Generate a C++ TokenKind -> SemanticTokenType switch from a text mapping.

Input format accepted:

    Identifier: "variable",
    SystemIdentifier: "function",
    OpenBrace: null,

By default, entries mapped to null are omitted and fall through to default
std::nullopt.

Example:

    python3 gen_semantic_token_switch.py mapping.txt \
        --function-name classifySemanticTokenKind \
        --token-scope slang::parsing::TokenKind \
        --semantic-scope SemanticTokenType \
        -o SemanticTokenSwitch.inc
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ENTRY_RE = re.compile(
    r"""^\s*
        (?P<token>[A-Za-z_][A-Za-z0-9_]*)
        \s*:\s*
        (?:
            "(?P<semantic>[A-Za-z_][A-Za-z0-9_]*)"
            |
            (?P<null>null)
        )
        \s*,?\s*
        (?://.*)?$
    """,
    re.VERBOSE,
)


SEMANTIC_ENUM_OVERRIDES = {
    # VS Code defaults
    "namespace": "Namespace",
    "class": "Class",
    "enum": "Enum",
    "interface": "Interface",
    "struct": "Struct",
    "typeParameter": "TypeParameter",
    "type": "Type",
    "parameter": "Parameter",
    "variable": "Variable",
    "property": "Property",
    "enumMember": "EnumMember",
    "decorator": "Decorator",
    "event": "Event",
    "function": "Function",
    "method": "Method",
    "macro": "Macro",
    "label": "Label",
    "comment": "Comment",
    "string": "String",
    "keyword": "Keyword",
    "number": "Number",
    "regexp": "Regexp",
    "operator": "Operator",
    # Custom SystemVerilog types
    "systemTask": "SystemTask",
    "directive": "Directive",
    "netType": "NetType",
    "port": "Port",
    "instance": "Instance",
    "modport": "Modport",
    "coverpoint": "Coverpoint",
    "constraint": "Constraint",
    "sequence": "Sequence",
    "clockingBlock": "ClockingBlock",
    "primitive": "Primitive",
}


def parse_mapping(text: str) -> list[tuple[str, str | None]]:
    """Parse mapping lines into (TokenKindName, semanticName | None)."""
    entries: list[tuple[str, str | None]] = []

    for line_no, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("//") or stripped.startswith("#"):
            continue

        match = ENTRY_RE.match(line)
        if not match:
            raise ValueError(f"Could not parse line {line_no}: {line!r}")

        token = match.group("token")
        semantic = match.group("semantic")
        entries.append((token, semantic))

    return entries


def semantic_to_enum_name(semantic: str) -> str:
    """Convert semantic token text to a C++ enum enumerator name."""
    if semantic in SEMANTIC_ENUM_OVERRIDES:
        return SEMANTIC_ENUM_OVERRIDES[semantic]

    # Fallback: lowerCamel / snake-ish to PascalCase.
    pieces = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", semantic).replace("_", " ").split()
    return "".join(piece[:1].upper() + piece[1:] for piece in pieces)


def generate_cpp(
    entries: list[tuple[str, str | None]],
    *,
    function_name: str,
    token_scope: str,
    semantic_scope: str,
    return_type: str,
    include_null_cases: bool,
    include_header: bool,
) -> str:
    lines: list[str] = []

    if include_header:
        lines.extend(
            [
                "// Generated by gen_semantic_token_switch.py. Do not edit by hand.",
                "#include <optional>",
                "#include <cstdint>",
                "",
            ]
        )

    lines.append(f"static {return_type} {function_name}({token_scope} kind) {{")
    lines.append("    switch (kind) {")

    for token, semantic in entries:
        case_line = f"        case {token_scope}::{token}:"
        if semantic is None:
            if include_null_cases:
                lines.append(case_line)
                lines.append("            return std::nullopt;")
            continue

        enum_name = semantic_to_enum_name(semantic)
        lines.append(case_line)
        lines.append(
            f"            return static_cast<uint32_t>({semantic_scope}::{enum_name});"
        )

    lines.append("        default:")
    lines.append("            return std::nullopt;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate C++ TokenKind -> SemanticTokenType switch from mapping text."
    )
    parser.add_argument(
        "-o", "--output", type=Path, help="Output C++ file. Defaults to stdout."
    )
    parser.add_argument(
        "--function-name",
        default="classifySemanticTokenKind",
        help="Generated C++ function name",
    )
    parser.add_argument(
        "--token-scope",
        default="slang::parsing::TokenKind",
        help="C++ enum scope for parser tokens",
    )
    parser.add_argument(
        "--semantic-scope",
        default="SemanticTokenType",
        help="C++ enum scope for semantic token types",
    )
    parser.add_argument(
        "--return-type",
        default="std::optional<uint32_t>",
        help="Generated function return type",
    )
    parser.add_argument(
        "--include-null-cases",
        action="store_true",
        help="Emit explicit cases for null mappings instead of relying on default",
    )
    parser.add_argument(
        "--include-header",
        action="store_true",
        help="Emit basic includes before the generated function",
    )

    args = parser.parse_args()

    input = Path(__file__).resolve().parent / "semantic_tokens.txt"

    mapping_text = input.read_text(encoding="utf-8")
    entries = parse_mapping(mapping_text)

    cpp = generate_cpp(
        entries,
        function_name=args.function_name,
        token_scope=args.token_scope,
        semantic_scope=args.semantic_scope,
        return_type=args.return_type,
        include_null_cases=args.include_null_cases,
        include_header=args.include_header,
    )

    if args.output:
        args.output.write_text(cpp, encoding="utf-8")
    else:
        print(cpp, end="")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
