ignores:
    - vscode # Provided by the VSCode runtime
    - markdownlint # Provides markdownlint/style/prettier
    - \@trivago/prettier-plugin-sort-imports # Used in format:prettier-eslint
    - prettier-plugin-organize-imports # Used in format:prettier
