#pragma once

#include "lsp/LspServer.h"
#include "semantic_tokens/SemanticToken.hpp"

#include "slang/parsing/TokenKind.h"

using namespace lsp;

static std::optional<uint32_t> classifySemanticTokenKind(slang::parsing::TokenKind kind) {
    switch (kind) {
        case slang::parsing::TokenKind::Identifier:
            return static_cast<uint32_t>(SemanticTokenType::Variable);
        case slang::parsing::TokenKind::SystemIdentifier:
            return static_cast<uint32_t>(SemanticTokenType::Function);
        case slang::parsing::TokenKind::StringLiteral:
            return static_cast<uint32_t>(SemanticTokenType::String);
        case slang::parsing::TokenKind::IntegerLiteral:
            return static_cast<uint32_t>(SemanticTokenType::Number);
        case slang::parsing::TokenKind::IntegerBase:
            return static_cast<uint32_t>(SemanticTokenType::Number);
        case slang::parsing::TokenKind::UnbasedUnsizedLiteral:
            return static_cast<uint32_t>(SemanticTokenType::Number);
        case slang::parsing::TokenKind::RealLiteral:
            return static_cast<uint32_t>(SemanticTokenType::Number);
        case slang::parsing::TokenKind::TimeLiteral:
            return static_cast<uint32_t>(SemanticTokenType::Number);
        case slang::parsing::TokenKind::Placeholder:
            return static_cast<uint32_t>(SemanticTokenType::String);
        case slang::parsing::TokenKind::Apostrophe:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::ApostropheOpenBrace:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Colon:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::ColonEquals:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::ColonSlash:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::DoubleColon:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Dot:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Slash:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Star:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::DoubleStar:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::StarArrow:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Plus:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::DoublePlus:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::PlusColon:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::PlusDivMinus:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::PlusModMinus:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Minus:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::DoubleMinus:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::MinusColon:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::MinusArrow:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::MinusDoubleArrow:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Tilde:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::TildeAnd:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::TildeOr:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::TildeXor:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Dollar:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Question:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Hash:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::DoubleHash:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::HashMinusHash:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::HashEqualsHash:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Xor:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::XorTilde:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Equals:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::DoubleEquals:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::DoubleEqualsQuestion:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::TripleEquals:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::EqualsArrow:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::PlusEqual:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::MinusEqual:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::SlashEqual:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::StarEqual:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::AndEqual:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::OrEqual:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::PercentEqual:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::XorEqual:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::LeftShiftEqual:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::TripleLeftShiftEqual:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::RightShiftEqual:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::TripleRightShiftEqual:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::LeftShift:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::RightShift:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::TripleLeftShift:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::TripleRightShift:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Exclamation:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::ExclamationEquals:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::ExclamationEqualsQuestion:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::ExclamationDoubleEquals:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Percent:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::LessThan:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::LessThanEquals:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::LessThanMinusArrow:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::GreaterThan:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::GreaterThanEquals:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::Or:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::DoubleOr:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::OrMinusArrow:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::OrEqualsArrow:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::At:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::DoubleAt:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::And:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::DoubleAnd:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::TripleAnd:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::OneStep:
            return static_cast<uint32_t>(SemanticTokenType::Number);
        case slang::parsing::TokenKind::AcceptOnKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::AliasKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::AlwaysKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::AlwaysCombKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::AlwaysFFKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::AlwaysLatchKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::AndKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::AssertKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::AssignKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::AssumeKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::AutomaticKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::BeforeKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::BeginKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::BindKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::BinsKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::BinsOfKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::BitKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::BreakKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::BufKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::BufIf0Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::BufIf1Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ByteKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::CaseKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::CaseXKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::CaseZKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::CellKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::CHandleKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::CheckerKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ClassKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ClockingKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::CmosKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ConfigKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ConstKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ConstraintKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ContextKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ContinueKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::CoverKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::CoverGroupKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::CoverPointKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::CrossKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::DeassignKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::DefaultKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::DefParamKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::DesignKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::DisableKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::DistKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::DoKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EdgeKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ElseKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndCaseKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndCheckerKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndClassKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndClockingKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndConfigKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndFunctionKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndGenerateKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndGroupKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndInterfaceKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndModuleKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndPackageKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndPrimitiveKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndProgramKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndPropertyKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndSpecifyKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndSequenceKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndTableKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EndTaskKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EnumKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::EventKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::EventuallyKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::ExpectKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ExportKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ExtendsKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ExternKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::FinalKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::FirstMatchKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::ForKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ForceKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ForeachKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ForeverKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ForkKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ForkJoinKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::FunctionKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::GenerateKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::GenVarKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::GlobalKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Namespace);
        case slang::parsing::TokenKind::HighZ0Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::HighZ1Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::IfKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::IffKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::IfNoneKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::IgnoreBinsKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::IllegalBinsKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ImplementsKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ImpliesKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::ImportKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::IncDirKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::IncludeKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::InitialKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::InOutKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::InputKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::OutputKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::RefKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::InsideKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::InstanceKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::IntKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::IntegerKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::InterconnectKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::InterfaceKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::IntersectKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::JoinKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::JoinAnyKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::JoinNoneKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::LargeKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::LetKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::LibListKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::LibraryKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::LocalKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::LocalParamKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::LogicKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::LongIntKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::MacromoduleKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::MatchesKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::MediumKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ModPortKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ModuleKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::NandKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::NegEdgeKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::NetTypeKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::NewKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::NextTimeKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::NmosKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::NorKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::NoShowCancelledKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::NotKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::NotIf0Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::NotIf1Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::NullKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::OrKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::PackageKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::PackedKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ParameterKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::PmosKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::PosEdgeKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::PrimitiveKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::PriorityKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ProgramKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::PropertyKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ProtectedKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::Pull0Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::Pull1Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::PullDownKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::PullUpKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::PulseStyleOnDetectKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::PulseStyleOnEventKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::PureKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::RandKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::RandCKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::RandCaseKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::RandSequenceKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::RcmosKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::RealKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::RealTimeKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::RegKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::RejectOnKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ReleaseKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::RepeatKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::RestrictKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ReturnKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::RnmosKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::RpmosKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::RtranKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::RtranIf0Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::RtranIf1Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::SAlwaysKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::SEventuallyKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::SNextTimeKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::SUntilKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::SUntilWithKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::ScalaredKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::SequenceKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ShortIntKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::ShortRealKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::ShowCancelledKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::SignedKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::SmallKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::SoftKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::SolveKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::SpecifyKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::SpecParamKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::StaticKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::StringKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::StrongKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::Strong0Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::Strong1Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::StructKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::SuperKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::Supply0Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::Supply1Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::SyncAcceptOnKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::SyncRejectOnKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::TableKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::TaggedKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::TaskKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ThisKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::ThroughoutKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::TimeKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::TimePrecisionKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::TimeUnitKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::TranKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::TranIf0Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::TranIf1Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::TriKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::Tri0Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::Tri1Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::TriAndKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::TriOrKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::TriRegKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::TypeKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::TypedefKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::UnionKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::UniqueKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::Unique0Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::UnsignedKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::UntilKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::UntilWithKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::UntypedKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::UseKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::UWireKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::VarKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::VectoredKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::VirtualKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::VoidKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::WaitKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::WaitOrderKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::WAndKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::WeakKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::Weak0Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::Weak1Keyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::WhileKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::WildcardKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::WireKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::WithKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::WithinKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::WOrKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Type);
        case slang::parsing::TokenKind::XnorKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::XorKeyword:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::UnitSystemName:
            return static_cast<uint32_t>(SemanticTokenType::Namespace);
        case slang::parsing::TokenKind::RootSystemName:
            return static_cast<uint32_t>(SemanticTokenType::Namespace);
        case slang::parsing::TokenKind::Directive:
            return static_cast<uint32_t>(SemanticTokenType::Keyword);
        case slang::parsing::TokenKind::IncludeFileName:
            return static_cast<uint32_t>(SemanticTokenType::String);
        case slang::parsing::TokenKind::MacroUsage:
            return static_cast<uint32_t>(SemanticTokenType::Macro);
        case slang::parsing::TokenKind::MacroQuote:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::MacroTripleQuote:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::MacroEscapedQuote:
            return static_cast<uint32_t>(SemanticTokenType::String);
        case slang::parsing::TokenKind::MacroPaste:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        case slang::parsing::TokenKind::LineContinuation:
            return static_cast<uint32_t>(SemanticTokenType::Operator);
        default:
            return std::nullopt;
    }
}