name: Deploy PR Preview to gh-pages

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yaml'
  workflow_dispatch:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.17"
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Build docs
        run: uv run mkdocs build --strict
      - name: Deploy to gh-pages preview directory
        # This step is much more complex than a simple push
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          destination_dir: previews/pr-${{ github.event.number }}

      - name: Comment preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = `https://hudson-trading.github.io/slang-server/previews/pr-${{ github.event.number }}/`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `📖 Documentation preview deployed: ${previewUrl}`
            });
